on : push
jobs :
    release :
        runs-on : ubuntu-latest
        steps :
        - uses : actions/checkout@main
        - run : docker build -t 2json .
        - run : docker save 2json > 2json.tar
        - run : docker image prune --all
