on: push
permissions:
    contents: write
jobs:
    release:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            IMAGE: ${{ github.event.repository.name }}.image.tar
        steps:
        - env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        #- run: gh repo clone "${{ github.repository }}" .
        - uses: action/checkout@${{ github.ref_name }}
        - run: docker build -t "${{ github.event.repository.name }}" .
        - run: docker save "${{ github.event.repository.name }}" > "$IMAGE"
        - run: gh -y delete "${{ github.ref_name }}" || true
        - run: gh release create "${{ github.ref_name }}" --generate-notes
        - run: gh release upload "${{ github.ref_name }}" "$IMAGE"
