on : push
jobs :
    release :
        runs-on : ubuntu-latest
        env :
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps :
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
        - run : gh repo clone "${{ github.repository }}" .
        - run : docker build -t "${{ github.event.repository.name }}"
        - run : docker save "${{ github.event.repository.name }}" > "${{ github.event.repository.name }}".image.tar
